-- Generated by scripts/build-seed-sql.py — do not edit by hand.
-- Patrick's real roster, in the platform's shape.

begin;

insert into agency (id, slug, name, brand, plan, subscription_status, application_fee_bps, network_enabled) values
  ('895283e1-7886-5868-89d0-b31a8b0dd695', 'unicorn-club', 'Unicorn Club', '{"displayName": "Unicorn Club", "logoUrl": "/unicorn-club-logo.png", "cream": "#F1EDE5", "panel": "#F6F3EC", "inputBg": "#F8F5EF", "ink": "#1B1A17", "text2": "#6b6457", "textMuted": "#9a9486", "serif": "Newsreader", "sans": "Hanken Grotesk", "confidentialityNote": "Confidential \u2014 please do not share under any circumstances."}'::jsonb, 'studio', 'trialing', 500, true)
on conflict (id) do nothing;

insert into agency_member (id, agency_id, name, email, role) values
  ('117c2275-0241-56ba-a216-b226f7b746bc', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Mags', 'mags@unicornclub.example', 'owner')
on conflict (id) do nothing;

insert into client (id, agency_id, name, active) values
  ('fb877c7f-853d-5624-a3e1-aabd2a624f9c', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Patrick', true)
on conflict (id) do nothing;

insert into client_city (id, client_id, key, label, position) values
  ('84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'fb877c7f-853d-5624-a3e1-aabd2a624f9c', 'new-york', 'New York', 0),
  ('bbe7afe2-b92e-55ad-9958-c375f5b09ea9', 'fb877c7f-853d-5624-a3e1-aabd2a624f9c', 'miami', 'Miami', 1),
  ('1fc853cc-c704-569a-87d1-df3e99724bf3', 'fb877c7f-853d-5624-a3e1-aabd2a624f9c', 'los-angeles', 'Los Angeles', 2),
  ('0dce2cdd-ae00-58f0-8394-5a1ef543dc29', 'fb877c7f-853d-5624-a3e1-aabd2a624f9c', 'elsewhere-abroad', 'Elsewhere/Abroad', 3),
  ('9d07fac3-d6a3-591d-9cf2-fbe82e6b5933', 'fb877c7f-853d-5624-a3e1-aabd2a624f9c', 'prior-partners', 'Prior Partners', 4)
on conflict (id) do nothing;

insert into candidate (id, agency_id, name, age, based_in, profession, faith, about) values
  ('d0663f5a-75c3-576a-9c7c-7a5d75b881bd', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Stephanie C', '35', 'New York', 'Operations @ VC Firm', 'Christian', 'Stephanie is smart, beautiful, and confident, with a natural poise and outgoing energy. She recently moved back to New York for her role at a VC firm. She knows what she''s looking for and is clear that she wants a family.'),
  ('12e795b7-274b-5e26-bb3b-6ce22cb807aa', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Selin U', '30', 'New York', 'Business Program Manager', 'Christian', 'Raised in Northern Virginia with deep Turkish family roots, Selin leads strategic technology initiatives remotely and graduated at the top of her class. Outside work she balances tennis, Sunday baking, yoga, and photography with a love of classic literature and travel. Friends call her thoughtful, adventurous, and graceful. Height 5''7". Looking for someone kind, ambitious, and ready to build a real connection.'),
  ('4b7b7d51-15e7-561e-9be7-e75c157bc690', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Katya D', '30', 'Miami', 'Profile Miami Co-Founder & Development Sales', 'Christian', 'Katya grew up in LA and moved to New York (her father has a senior role at a hedgefund) and she is in NYC semi often for work. Open to moving back to the city especially because her family is so close. She has an infectious happy energy and is a talented person - she plays piano, sings and'),
  ('7ea0eb8b-117f-5dee-a5b1-df32e29f1633', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Sabrina S', '33', 'New York', 'Founder, luxury travel consultancy (superyacht charters)', '', 'Sabrina grew up immersed in the yachting world as the daughter of a well-known yachting journalist, and has built her own boutique consultancy managing global travel for private charter clients. She''s known for creating unforgettable experiences. Discerning, resourceful, and composed, she brings taste and intuition to everything she does.'),
  ('3f41f84a-8bc8-533a-b9e7-8818be3f3cf6', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Morgan D', '29', 'New York City', 'Civil Engineer', 'Catholic', 'Kind, smart and just a solid person overall. She has her own career and life but is commitment oriented and ready for family. Referred by a very close friend and waiting to interview her upon request.'),
  ('54fabef1-8614-5d50-9454-93783338d937', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Sofia S', '24', 'New York', 'DJ & Model', 'Christian', 'Sofia is hard working, from a nice family and knows how to have fun. Only recently single. Maybe not the right type but has a sizable network of friends her age.'),
  ('b2bb91f3-8fc2-50c4-a4e1-baa837d525ef', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Madison', '31', 'New York', 'Attorney', '', 'Madison is an attorney and native New Yorker. She loves travel and adventure and is an avid NYC sports fan. Family is central to her life and she''s especially close with her older brothers, nieces, and nephews. She loves a dance floor. Height 5''6".'),
  ('5ab5b034-8486-5917-8851-528b5e0a95a4', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Solenne "Twiga"', '30', 'Miami', 'Material Good', 'Catholic', 'Former successful natural red head model. (Her look is not for everyone but she is a very unique beauty.) Innate sense of style. Senior at Material Good. Equestrian.'),
  ('00991521-7dd9-5ec4-bde1-c8dd58dbd7c7', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Bailey T', '28', 'Los Angeles', 'Photographer', 'Christian', 'Frequently in NYC for work but based in LA. Would move for the right person. Bailey is a natural beauty and real talent. Sober'),
  ('02607c36-113b-51a7-9a8d-1a696af86388', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Erica', '33', 'Los Angeles', 'Tech founder & angel investor', 'Christian', 'A former Miss New York turned tech founder, strategist, and angel investor, Erica pairs a powerful résumé with an equally powerful heart. Originally from the Midwest, she brings grace, warmth, and depth to everything she touches. She mentors youth, hosts a wellness podcast, and is an accomplished tri-athlete — riding horses, curating art, or deep in a new book, she lives with intention. Height 5''6". She''s ready for a partner who values strength, softness, and a shared vision for a beautiful life.'),
  ('19ecdc70-5347-5d15-b961-df39e7e0376b', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Ashleigh S', '37', 'Miami', 'Dermatologist', 'Jewish - not religious', 'Ashleigh is very family oriented, has accomplished a lot professionally and would be willing to relocate for the right person. She is tall (5''10") curvy and beautiful,'),
  ('6245e4f4-b012-5fab-a2c2-7ec1c3f7645f', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Sandra W', '33', 'New York City', 'Director, screenwriter & photographer', '', 'Sandra is a Danish director, screenwriter, and photographer based in New York. Her debut feature Lowland Kids, produced by Darren Aronofsky''s Protozoa Pictures, premiered at CPH:DOX, with a theatrical release coming in 2026. Her documentary A New Wave ran as a New York Times Op-Doc in 2024.'),
  ('c689e68b-beed-5320-bfe8-98afe53113d4', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Johanna D', '38', 'Miami', 'Head of retail Ventures @ Starwood and co-owner of furniture, home and lifestyle brand', 'Jewish', 'You wouldn''t expect someone as effortlessly chic as Johanna to also be so approachable and kind. She is a very passionate woman. A few years older than ideal so will hold for now.

https://sheerluxe.com/ultraluxe/ransom-and-dunn'),
  ('f0231e4b-77c0-523b-a4e2-9efe788de2a9', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Danna H', '30', 'Miami', 'Former Ms. Puerto Rico, influencer', 'Catholic', ''),
  ('126374d1-5936-5865-aee4-caaaff13b991', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Natalia', '35', 'New York', 'Real Estate', '', 'Real estate professional based in NYC, but passing for now because though she filled out the questionnaire she hasn''t responded to me yet.'),
  ('20e51392-4a5f-5e0d-b5ed-408aa3d31e46', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Monica M', '33', 'Miami', 'Producer', 'Christian', 'Bilingual'),
  ('010d5fde-c563-5976-9089-d6a498204e88', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Micaela E', '39', 'New York City', 'Stylist', 'Christian', 'Amazing person at the top of her game professionally. Just turned 40 so likely too old but she is lovely. Eager to have a family.

https://micaelaerlanger.com/about/'),
  ('44f5148e-50bf-5278-8798-8e5a494470c4', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Allyson Sabbagh', '', 'New York', 'Real Estate & Investor', 'Jewish', ''),
  ('955eb6bd-6d1b-5961-b7b0-52e6b57ae386', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Sydney K', '', 'New York', '', '', '')
on conflict (id) do nothing;

insert into candidate_internal (candidate_id, agency_id, ig, source) values
  ('d0663f5a-75c3-576a-9c7c-7a5d75b881bd', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('12e795b7-274b-5e26-bb3b-6ce22cb807aa', '895283e1-7886-5868-89d0-b31a8b0dd695', '', 'Steph Chubin'),
  ('4b7b7d51-15e7-561e-9be7-e75c157bc690', '895283e1-7886-5868-89d0-b31a8b0dd695', '', 'know personally'),
  ('7ea0eb8b-117f-5dee-a5b1-df32e29f1633', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('3f41f84a-8bc8-533a-b9e7-8818be3f3cf6', '895283e1-7886-5868-89d0-b31a8b0dd695', '@morgansdownie', 'Keith George'),
  ('54fabef1-8614-5d50-9454-93783338d937', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('b2bb91f3-8fc2-50c4-a4e1-baa837d525ef', '895283e1-7886-5868-89d0-b31a8b0dd695', '', 'Beth Mandell/ Lisa Clampitt'),
  ('5ab5b034-8486-5917-8851-528b5e0a95a4', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('00991521-7dd9-5ec4-bde1-c8dd58dbd7c7', '895283e1-7886-5868-89d0-b31a8b0dd695', '', 'Questionnaire'),
  ('02607c36-113b-51a7-9a8d-1a696af86388', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('19ecdc70-5347-5d15-b961-df39e7e0376b', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('6245e4f4-b012-5fab-a2c2-7ec1c3f7645f', '895283e1-7886-5868-89d0-b31a8b0dd695', '@sandrawinther', 'Anna Shimonis'),
  ('c689e68b-beed-5320-bfe8-98afe53113d4', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('f0231e4b-77c0-523b-a4e2-9efe788de2a9', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('126374d1-5936-5865-aee4-caaaff13b991', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('20e51392-4a5f-5e0d-b5ed-408aa3d31e46', '895283e1-7886-5868-89d0-b31a8b0dd695', '', 'Know personally'),
  ('010d5fde-c563-5976-9089-d6a498204e88', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('44f5148e-50bf-5278-8798-8e5a494470c4', '895283e1-7886-5868-89d0-b31a8b0dd695', '', ''),
  ('955eb6bd-6d1b-5961-b7b0-52e6b57ae386', '895283e1-7886-5868-89d0-b31a8b0dd695', '', '')
on conflict (candidate_id) do nothing;

insert into roster (id, agency_id, client_id, title, status, shared_at) values
  ('2697a1d1-335a-58a4-8d89-613b3c2dee44', '895283e1-7886-5868-89d0-b31a8b0dd695', 'fb877c7f-853d-5624-a3e1-aabd2a624f9c', 'Introductions', 'shared', '2026-08-21T12:00:00Z')
on conflict (id) do nothing;

insert into roster_item (id, roster_id, candidate_id, city_id, status, blurb, position) values
  ('e64a9d01-23b1-5a2d-9e64-6784a9f22fca', '2697a1d1-335a-58a4-8d89-613b3c2dee44', 'd0663f5a-75c3-576a-9c7c-7a5d75b881bd', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'maybe', 'Smart, beautiful, just moved back to NYC.', 0),
  ('d92684ee-46a3-5a47-b36a-0d4e6a2dd947', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '12e795b7-274b-5e26-bb3b-6ce22cb807aa', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'maybe', 'Sophisticated and playful, with depth — thoughtful, adventurous and graceful.', 1),
  ('cd0e363c-642c-5f3e-8945-5e3fd50117dd', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '4b7b7d51-15e7-561e-9be7-e75c157bc690', 'bbe7afe2-b92e-55ad-9958-c375f5b09ea9', 'hold', 'Talented, warm, smart, down to earth, petite, curvy, hilarious.', 2),
  ('bedd3a05-df95-5ae5-96a2-39792d3e1585', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '7ea0eb8b-117f-5dee-a5b1-df32e29f1633', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'maybe', 'Worldly and resourceful, with an insider''s eye for the extraordinary.', 3),
  ('1e94c2ad-8491-5587-a81b-41adb748bb07', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '3f41f84a-8bc8-533a-b9e7-8818be3f3cf6', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'maybe', 'Adorable, successful and ready for true partnership.', 4),
  ('63280d3b-538a-5dd5-bfc9-d8a7f61e128a', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '54fabef1-8614-5d50-9454-93783338d937', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'maybe', 'Sweet, beautiful, friendly and cool.', 5),
  ('b2fae496-460d-569d-8d0b-1b9ae834a44f', '2697a1d1-335a-58a4-8d89-613b3c2dee44', 'b2bb91f3-8fc2-50c4-a4e1-baa837d525ef', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'maybe', 'Kind, smart, and outgoing — a native New Yorker attorney with a big heart for family and friends.', 6),
  ('9c0f1067-d228-5fde-95ea-614c77da2a3d', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '5ab5b034-8486-5917-8851-528b5e0a95a4', 'bbe7afe2-b92e-55ad-9958-c375f5b09ea9', 'hold', 'Smart, unique, sophisticated French girl in Miami.', 7),
  ('c684b2f1-5a55-5cf4-b529-b6a03cea2da6', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '00991521-7dd9-5ec4-bde1-c8dd58dbd7c7', '1fc853cc-c704-569a-87d1-df3e99724bf3', 'hold', 'down to earth, sweet natured professional photographer. Frequently in nyc', 8),
  ('ca4acbed-62a3-5bd6-bab6-3bbcf6b1c4f9', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '02607c36-113b-51a7-9a8d-1a696af86388', '1fc853cc-c704-569a-87d1-df3e99724bf3', 'hold', 'Feminine, sophisticated, and driven — a former Miss New York turned tech founder with real depth of character.', 9),
  ('7fd72cc1-a90b-583c-8c60-b0d999af21c5', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '19ecdc70-5347-5d15-b961-df39e7e0376b', 'bbe7afe2-b92e-55ad-9958-c375f5b09ea9', 'maybe', 'Unicorn doctor', 10),
  ('e5960232-7f11-5d83-8735-9aac1cb70fb6', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '6245e4f4-b012-5fab-a2c2-7ec1c3f7645f', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'passed', 'A Danish filmmaker with a bold, cinematic eye.', 11),
  ('d30c3413-1e71-559e-b887-297b4f829492', '2697a1d1-335a-58a4-8d89-613b3c2dee44', 'c689e68b-beed-5320-bfe8-98afe53113d4', 'bbe7afe2-b92e-55ad-9958-c375f5b09ea9', 'hold', 'True badass: smart, beautiful, petite, successful.', 12),
  ('d8894519-e616-5866-96a4-a085e878d3db', '2697a1d1-335a-58a4-8d89-613b3c2dee44', 'f0231e4b-77c0-523b-a4e2-9efe788de2a9', 'bbe7afe2-b92e-55ad-9958-c375f5b09ea9', 'hold', '', 13),
  ('d1ccb6e3-4d60-51fd-bcda-dae0c1c93d93', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '126374d1-5936-5865-aee4-caaaff13b991', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'passed', '', 14),
  ('6084bb3b-71ab-5c27-953f-37d49bb76987', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '20e51392-4a5f-5e0d-b5ed-408aa3d31e46', 'bbe7afe2-b92e-55ad-9958-c375f5b09ea9', 'passed', 'Smart, quick witted, sophisticated.', 15),
  ('ed5f4f9d-4c2d-528e-9602-1e1eee243353', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '010d5fde-c563-5976-9089-d6a498204e88', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'passed', '', 16),
  ('35b44ba9-2689-5d6e-b343-be2cdf18bdf0', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '44f5148e-50bf-5278-8798-8e5a494470c4', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'passed', '', 17),
  ('1f6d67f8-c8da-5361-bd49-9528ee05a042', '2697a1d1-335a-58a4-8d89-613b3c2dee44', '955eb6bd-6d1b-5961-b7b0-52e6b57ae386', '84aefaf8-9715-55cd-85cb-33bfc8c9d496', 'maybe', '', 18)
on conflict (id) do nothing;

-- Private notes live in their own table; no client role has a policy on it.
insert into roster_item_private (roster_item_id, note) values
  ('bedd3a05-df95-5ae5-96a2-39792d3e1585', 'Background per Forbes profile (Aug 2025), "The Superyacht Lifestyle Architect."'),
  ('9c0f1067-d228-5fde-95ea-614c77da2a3d', 'Miami based so unsure'),
  ('ca4acbed-62a3-5bd6-bab6-3bbcf6b1c4f9', 'From Beth Mandell/ Lisa Clampit')
on conflict (roster_item_id) do nothing;

insert into booking_type (id, agency_id, name, kind, duration_min, price_cents) values
  ('0615fabb-4c05-591b-9b88-dc248bf720dc', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Intake conversation', 'intake', 60, 0),
  ('4ac571cb-1425-598a-be90-5bf085c87334', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Introduction', 'introduction', 90, 0),
  ('892923a0-8089-5b35-8c8d-497cf2bb92e9', '895283e1-7886-5868-89d0-b31a8b0dd695', 'Check-in', 'checkin', 30, 0)
on conflict (id) do nothing;

commit;
