#!/usr/bin/env python3
"""
Render data/seed-unicorn-club.json as SQL for a fresh Supabase project.

Run:  python3 scripts/build-seed-sql.py > supabase/seed.sql

Apply after 0001_schema.sql and 0002_rls.sql, as the service role (the SQL
editor in the Supabase dashboard, or `supabase db reset`). The auth_user_id
columns stay null: they are filled in when the matchmaker and the client each
accept their invite, which is what ties row-level security to a real person.
"""
import json, pathlib, sys

seed = json.loads(pathlib.Path("data/seed-unicorn-club.json").read_text())

def q(v):
    if v is None: return "null"
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

def rows(table, cols, records):
    if not records: return ""
    body = ",\n  ".join("(" + ", ".join(q(r.get(c)) for c in cols) + ")" for r in records)
    return f"insert into {table} ({', '.join(cols)}) values\n  {body}\non conflict (id) do nothing;\n\n"

out = ["-- Generated by scripts/build-seed-sql.py — do not edit by hand.\n",
       "-- Patrick's real roster, in the platform's shape.\n\n", "begin;\n\n"]

a = seed["agency"]
out.append(
    "insert into agency (id, slug, name, brand, plan, subscription_status, "
    "application_fee_bps, network_enabled) values\n  ("
    + ", ".join([q(a["id"]), q(a["slug"]), q(a["name"]),
                 q(json.dumps(a["brand"])) + "::jsonb", q(a["plan"]),
                 q(a["subscriptionStatus"]), str(a["applicationFeeBps"]),
                 q(a["networkEnabled"])])
    + ")\non conflict (id) do nothing;\n\n")

out.append(rows("agency_member", ["id", "agency_id", "name", "email", "role"],
                [{"id": m["id"], "agency_id": m["agencyId"], "name": m["name"],
                  "email": m["email"], "role": m["role"]} for m in seed["members"]]))

out.append(rows("client", ["id", "agency_id", "name", "active"],
                [{"id": c["id"], "agency_id": c["agencyId"], "name": c["name"],
                  "active": c["active"]} for c in seed["clients"]]))

out.append(rows("client_city", ["id", "client_id", "key", "label", "position"],
                [{"id": c["id"], "client_id": c["clientId"], "key": c["key"],
                  "label": c["label"], "position": c["position"]} for c in seed["cities"]]))

out.append(rows("candidate",
                ["id", "agency_id", "name", "age", "based_in", "profession", "faith", "about"],
                [{"id": c["id"], "agency_id": c["agencyId"], "name": c["name"], "age": c["age"],
                  "based_in": c["basedIn"], "profession": c["profession"], "faith": c["faith"],
                  "about": c["about"]} for c in seed["candidates"]]))

internal = [{"candidate_id": r["candidateId"], "agency_id": a["id"],
             "ig": r["ig"], "source": r["source"]} for r in seed["candidateInternal"]]
body = ",\n  ".join("(" + ", ".join(q(r[c]) for c in ["candidate_id", "agency_id", "ig", "source"]) + ")"
                    for r in internal)
out.append("insert into candidate_internal (candidate_id, agency_id, ig, source) values\n  "
           + body + "\non conflict (candidate_id) do nothing;\n\n")

out.append(rows("roster", ["id", "agency_id", "client_id", "title", "status", "shared_at"],
                [{"id": r["id"], "agency_id": r["agencyId"], "client_id": r["clientId"],
                  "title": r["title"], "status": r["status"], "shared_at": r["sharedAt"]}
                 for r in seed["rosters"]]))

out.append(rows("roster_item",
                ["id", "roster_id", "candidate_id", "city_id", "status", "blurb", "position"],
                [{"id": i["id"], "roster_id": i["rosterId"], "candidate_id": i["candidateId"],
                  "city_id": i["cityId"], "status": i["status"], "blurb": i["blurb"],
                  "position": i["position"]} for i in seed["rosterItems"]]))

private = [i for i in seed["rosterItems"] if i["privateNote"]]
if private:
    body = ",\n  ".join(f"({q(i['id'])}, {q(i['privateNote'])})" for i in private)
    out.append("-- Private notes live in their own table; no client role has a policy on it.\n"
               "insert into roster_item_private (roster_item_id, note) values\n  "
               + body + "\non conflict (roster_item_id) do nothing;\n\n")

out.append(rows("booking_type", ["id", "agency_id", "name", "kind", "duration_min", "price_cents"],
                [{"id": b["id"], "agency_id": b["agencyId"], "name": b["name"], "kind": b["kind"],
                  "duration_min": b["durationMin"], "price_cents": b["priceCents"]}
                 for b in seed["bookingTypes"]]))

out.append("commit;\n")
sys.stdout.write("".join(out))
